/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminEarningsRouteImport } from './routes/admin.earnings'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarningsRoute = AdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/staff'
    | '/admin/earnings'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/earnings'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/staff'
    | '/admin/earnings'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/earnings': {
      id: '/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AdminEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEarningsRoute: typeof AdminEarningsRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEarningsRoute: AdminEarningsRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
