/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffInvoicesRouteImport } from './routes/staff.invoices'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminEarningsRouteImport } from './routes/admin.earnings'
import { Route as AdminStaffIndexRouteImport } from './routes/admin.staff.index'
import { Route as StaffInvoicesYearMonthRouteImport } from './routes/staff.invoices.$yearMonth'
import { Route as AdminStaffUserIdRouteImport } from './routes/admin.staff.$userId'
import { Route as AdminInvoicesUserIdYearMonthRouteImport } from './routes/admin.invoices.$userId.$yearMonth'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffInvoicesRoute = StaffInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => StaffRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarningsRoute = AdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStaffRoute,
} as any)
const StaffInvoicesYearMonthRoute = StaffInvoicesYearMonthRouteImport.update({
  id: '/$yearMonth',
  path: '/$yearMonth',
  getParentRoute: () => StaffInvoicesRoute,
} as any)
const AdminStaffUserIdRoute = AdminStaffUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminStaffRoute,
} as any)
const AdminInvoicesUserIdYearMonthRoute =
  AdminInvoicesUserIdYearMonthRouteImport.update({
    id: '/$userId/$yearMonth',
    path: '/$userId/$yearMonth',
    getParentRoute: () => AdminInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/staff/invoices': typeof StaffInvoicesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/staff/$userId': typeof AdminStaffUserIdRoute
  '/staff/invoices/$yearMonth': typeof StaffInvoicesYearMonthRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/invoices/$userId/$yearMonth': typeof AdminInvoicesUserIdYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/staff/invoices': typeof StaffInvoicesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/staff/$userId': typeof AdminStaffUserIdRoute
  '/staff/invoices/$yearMonth': typeof StaffInvoicesYearMonthRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/admin/invoices/$userId/$yearMonth': typeof AdminInvoicesUserIdYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRouteWithChildren
  '/staff/invoices': typeof StaffInvoicesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/staff/$userId': typeof AdminStaffUserIdRoute
  '/staff/invoices/$yearMonth': typeof StaffInvoicesYearMonthRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/invoices/$userId/$yearMonth': typeof AdminInvoicesUserIdYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/staff'
    | '/admin/earnings'
    | '/admin/invoices'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/staff/invoices'
    | '/admin/'
    | '/staff/'
    | '/admin/staff/$userId'
    | '/staff/invoices/$yearMonth'
    | '/admin/staff/'
    | '/admin/invoices/$userId/$yearMonth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/earnings'
    | '/admin/invoices'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin/settings'
    | '/staff/invoices'
    | '/admin'
    | '/staff'
    | '/admin/staff/$userId'
    | '/staff/invoices/$yearMonth'
    | '/admin/staff'
    | '/admin/invoices/$userId/$yearMonth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/staff'
    | '/admin/earnings'
    | '/admin/invoices'
    | '/admin/payroll'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/staff/invoices'
    | '/admin/'
    | '/staff/'
    | '/admin/staff/$userId'
    | '/staff/invoices/$yearMonth'
    | '/admin/staff/'
    | '/admin/invoices/$userId/$yearMonth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/invoices': {
      id: '/staff/invoices'
      path: '/invoices'
      fullPath: '/staff/invoices'
      preLoaderRoute: typeof StaffInvoicesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/earnings': {
      id: '/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AdminEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/staff/invoices/$yearMonth': {
      id: '/staff/invoices/$yearMonth'
      path: '/$yearMonth'
      fullPath: '/staff/invoices/$yearMonth'
      preLoaderRoute: typeof StaffInvoicesYearMonthRouteImport
      parentRoute: typeof StaffInvoicesRoute
    }
    '/admin/staff/$userId': {
      id: '/admin/staff/$userId'
      path: '/$userId'
      fullPath: '/admin/staff/$userId'
      preLoaderRoute: typeof AdminStaffUserIdRouteImport
      parentRoute: typeof AdminStaffRoute
    }
    '/admin/invoices/$userId/$yearMonth': {
      id: '/admin/invoices/$userId/$yearMonth'
      path: '/$userId/$yearMonth'
      fullPath: '/admin/invoices/$userId/$yearMonth'
      preLoaderRoute: typeof AdminInvoicesUserIdYearMonthRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
  }
}

interface AdminInvoicesRouteChildren {
  AdminInvoicesUserIdYearMonthRoute: typeof AdminInvoicesUserIdYearMonthRoute
}

const AdminInvoicesRouteChildren: AdminInvoicesRouteChildren = {
  AdminInvoicesUserIdYearMonthRoute: AdminInvoicesUserIdYearMonthRoute,
}

const AdminInvoicesRouteWithChildren = AdminInvoicesRoute._addFileChildren(
  AdminInvoicesRouteChildren,
)

interface AdminStaffRouteChildren {
  AdminStaffUserIdRoute: typeof AdminStaffUserIdRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
}

const AdminStaffRouteChildren: AdminStaffRouteChildren = {
  AdminStaffUserIdRoute: AdminStaffUserIdRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
}

const AdminStaffRouteWithChildren = AdminStaffRoute._addFileChildren(
  AdminStaffRouteChildren,
)

interface AdminRouteChildren {
  AdminEarningsRoute: typeof AdminEarningsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRouteWithChildren
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEarningsRoute: AdminEarningsRoute,
  AdminInvoicesRoute: AdminInvoicesRouteWithChildren,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffInvoicesRouteChildren {
  StaffInvoicesYearMonthRoute: typeof StaffInvoicesYearMonthRoute
}

const StaffInvoicesRouteChildren: StaffInvoicesRouteChildren = {
  StaffInvoicesYearMonthRoute: StaffInvoicesYearMonthRoute,
}

const StaffInvoicesRouteWithChildren = StaffInvoicesRoute._addFileChildren(
  StaffInvoicesRouteChildren,
)

interface StaffRouteChildren {
  StaffInvoicesRoute: typeof StaffInvoicesRouteWithChildren
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffInvoicesRoute: StaffInvoicesRouteWithChildren,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
