// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elvvyhxdahaldpdfsksd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdnZ5aHhkYWhhbGRwZGZza3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1ODM0NjIsImV4cCI6MjA5OTE1OTQ2Mn0.wOSVPCsdYZtWNqlZe-AJrk1ZY7P0KuLTguXsNktbDfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});